### ISSUE TITLE
Problem with CopyPaste from thronesDB

### ISSUE THREAD

**Issue by Duckbringer** [throneteki/throneteki-deck-helper#3]
When copying the decklist from thronesDB, sometimes cards are marked as restricted for Joust or Meele, deckbuilder on throneteki does not recognize cards with [J] or [M] behind them

I suggest treating line ending with these markings as if they did not have them

**Comment by EvadLhorg** [comment]
Hi! Thanks for the report, in the meantime you could try the following instead of manually removing the [X] parts:
In the top right of the deck view, click on Actions -> Plain Text. A new window will open from which you can easily copy and paste the decklist to throneteki.

**Comment by stopfstedt** [comment]
Hey, just chiming in to second what @EvadLhorg said in regards to using the export action as the failproof method for copy/pasting lists over. 

The restricted/banned list indicators will very likely remain a moving target (see recently added indicators for validation pods). I will try to stick with the "letters and numbers in brackets" template (should be doable to parse those out using regexp), but don't want to make any guarantees.

**Comment by ystros** [comment]
It doesn't appear the problem is the [J] or [M] markers, which was previously fixed, but the new pod markers (e.g. [P1]).
